### ISSUE TITLE
Can't decode with xdelta for file xxxx

### ISSUE THREAD

**Issue by MacLeek** [janavarro95/Stardew-Valley-Patch-Project#1]
Hi,
After I ran patcher.exe -O C:\SDV -P C:\source.zip, I got the error message
`Can't decode with xdelta for file StardewValley/MultiplayerUtility.cs.diff`  I'm also wandering what SDV version you are using to decompile.

**Comment by janavarro95** [comment]
Yea I understand this is currently a glitch. I'm currently debating
continuing to work on mods right now and if I do continue, the next update
would have a more detailed install info.

**Comment by janavarro95** [comment]
Also this is SDV 1.0.7

**Comment by MacLeek** [comment]
Finally I managed to run the game after removing GOG stuffs in the code.Hope you can continue on it!
